### ISSUE TITLE
draft-ietf-ippm-ioam-data-08 WGLC#1 comments: Clarifications to SHOULD statements 

### ISSUE THREAD

**Issue by brockners** [inband-oam/ietf#151]
- [Greg Mirsky]  In regard to the control over iOAM, text in Section 3 states "It SHOULD be possible to enable IOAM on a selected set of traffic ..." Does that mean that not providing the selective enabling of iOAM is an acceptable option? 
_Suggested approach: Add text detailing the “what if” you can’t make the SHOULD._ 

- [Greg Mirsky]  Further in Section 3, the requirement for encapsulation independence is using SHOULD "Data formats for IOAM SHOULD be defined in a transport-independent manner." What are the examples of exceptions? 
_Suggested approach: Add text detailing the “what if” you can’t make the SHOULD. Provide examples._

**Comment by inband-oam** [comment]
Greg Mirsky] In regard to the control over iOAM, text in Section 3 states "It SHOULD be possible to enable IOAM on a selected set of traffic ..." Does that mean that not providing the selective enabling of iOAM is an acceptable option?
Suggested approach: Add text detailing the “what if” you can’t make the SHOULD.
Describe what happens if selective traffic is not implemented .. perhaps rendering IOAM unusable

**Comment by inband-oam** [comment]
Greg Mirsky] Further in Section 3, the requirement for encapsulation independence is using SHOULD "Data formats for IOAM SHOULD be defined in a transport-independent manner." What are the examples of exceptions?

s/SHOULD/should , drop transport.. drop this whole line?

**Comment by inband-oam** [comment]
@brockners  to edit text and create a patch for this
