### ISSUE TITLE
IPv6 IOAM: 4n vs 8n+4 alignment

### ISSUE THREAD

**Issue by IurmanJ** [inband-oam/ietf#164]
In [draft-ietf-ippm-ioam-ipv6-options](https://tools.ietf.org/html/draft-ietf-ippm-ioam-ipv6-options-01), the following is said at the end of section 3:

> All the in-situ OAM IPv6 options defined here have alignment requirements.  Specifically, they all require 4n alignment.  This ensures that 4 octet fields specified in [I-D.ietf-ippm-ioam-data] such as transit delay are aligned at a multiple-of-4 offset from the start of the Hop-by-Hop Options header.  In addition, to maintain IPv6 extension header 8-octet alignment and avoid the need to add or remove padding at every hop, the Trace-Type for Incremental Tracing Option in IPv6 MUST be selected such that the IOAM node data length is a multiple of 8-octets.

There is nothing about 8-octet fields and it is assumed that all fields are in fact 4-octet fields (see also #106). Is it intentional to consider 8-octet fields as 4-octet fields? While I agree it simplifies the alignment problem of having a mix of 4 and 8 octet fields, shouldn't those 8-octet fields be represented in [draft-ietf-ippm-ioam-data](https://tools.ietf.org/html/draft-ietf-ippm-ioam-data-09) as 2 consecutive but distinct 4-octet fields then? This is only the case for wide (ingress_id, egress_id), not for others. Right now, it is quite confusing as those 8-octet fields may be misaligned.

Otherwise, if it wasn't intentional to omit them, those 8-octet fields should be positioned first in the trace type, before 4-octet fields. Indeed, this would prevent 8-octet fields to maybe appear in between 4-octet fields and so being misaligned. However, due to the option header (12 octets), an overall and good alignment would only be possible by defining an 8n+4 alignment (see example below).

```
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
|   EH NxtHdr   |   EH Length   |     Pad       |      Pad      |
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
|  Option Type  | Opt Data Len  |   Reserved    |   IOAM Type   |
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
|         Namespace-ID          | NodeLen | Flags |RemainingLen |
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
|               IOAM-Trace-Type                 |  Reserved     |
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
|                                                               |
~                         8-octet field                         ~
|                                                               |
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
|                                                               |
~                         8-octet field                         ~
|                                                               |
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
|                         4-octet field                         |
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
|                         4-octet field                         |
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
```

**Comment by mickeyspiegel** [comment]
The question is whether the 8-octet fields need to be aligned on 8-octet boundaries. If so, your suggestion of 8n+4 alignment would be necessary, along with reordering of the bits in IOAM-Trace-Type. If it is acceptable to align 8-octet fields only on 4-octet boundaries, then none of that would be required. I don't see a need to align on 8-octet boundaries in the implementations that I am familiar with.

**Comment by shwethab** [comment]
As mentioned in the text snippet from the draft the intention for the alignment is to :" to maintain IPv6 extension header 8-octet alignment and avoid the need to add or remove padding at every hop, the Trace-Type for Incremental Tracing Option in IPv6 MUST be selected such that the IOAM node data length is a multiple of 8-octets."
I dont see a need and  advantage in aligning 8-octet fields to 8-octet boundaries from an implementation perspective.

**Comment by IurmanJ** [comment]
> As mentioned in the text snippet from the draft the intention for the alignment is to :" to maintain IPv6 extension header 8-octet alignment and avoid the need to add or remove padding at every hop, the Trace-Type for Incremental Tracing Option in IPv6 MUST be selected such that the IOAM node data length is a multiple of 8-octets."
> I dont see a need and advantage in aligning 8-octet fields to 8-octet boundaries from an implementation perspective.

@shwethab IPv6 extension header 8-octet alignment is, of course, respected. But that does not mean what's inside is also well-aligned.

> The question is whether the 8-octet fields need to be aligned on 8-octet boundaries. If so, your suggestion of 8n+4 alignment would be necessary, along with reordering of the bits in IOAM-Trace-Type. If it is acceptable to align 8-octet fields only on 4-octet boundaries, then none of that would be required. I don't see a need to align on 8-octet boundaries in the implementations that I am familiar with.

@mickeyspiegel I'd say the question is more like: is this really a need or a choice we have here? Shouldn't we follow the recommendations of [RFC 8200](https://tools.ietf.org/html/rfc8200#appendix-A)? I mean, some architectures do not support (or not completely/well) bad data alignment. And for those who do, you'd still add an unnecessary overhead (access two memory words instead of one). 

However, if we keep going the current way, no matter what, I'd suggest to either update [draft-ietf-ippm-ioam-ipv6-options](https://tools.ietf.org/html/draft-ietf-ippm-ioam-ipv6-options-01) as follows:

`s/This ensures that 4 octet fields specified in/This ensures that fields specified in/` (Section 3, penultimate paragraph).

Or update graphical (and textual) representations of 8-octet fields of [draft-ietf-ippm-ioam-data](https://tools.ietf.org/html/draft-ietf-ippm-ioam-data-09#section-4.4.2): `wide (hop_lim, node_id)` and `wide namespace specific data`, such as `wide (ingress_if_id, egress_if_id)`, even if it splits the same field in two. For example, something like this:

```
   Hop_Lim and node_id wide:  2 consecutive 4-octet fields defined as follows:

    0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
   |   Hop_Lim     |              node_id                          |
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
   |                         node_id (contd)                       |
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+

      node_id:  (MSB) 3-octet unsigned integer; (LSB) 4-octet unsigned integer.
         Node identifier field to uniquely identify a node within the 
         IOAM-Namespace and associated IOAM-Domain.  The procedure 
         to allocate, manage and map the node_ids is beyond the scope of 
         this document.
```

**Comment by shwethab** [comment]
> @shwethab IPv6 extension header 8-octet alignment is, of course, respected. But that does not mean what's inside is also well-aligned.
> 
> > The question is whether the 8-octet fields need to be aligned on 8-octet boundaries. If so, your suggestion of 8n+4 alignment would be necessary, along with reordering of the bits in IOAM-Trace-Type. If it is acceptable to align 8-octet fields only on 4-octet boundaries, then none of that would be required. I don't see a need to align on 8-octet boundaries in the implementations that I am familiar with.
> 
> @mickeyspiegel I'd say the question is more like: is this really a need or a choice we have here? Shouldn't we follow the recommendations of [RFC 8200](https://tools.ietf.org/html/rfc8200#appendix-A)? I mean, some architectures do not support (or not completely/well) bad data alignment. And for those who do, you'd still add an unnecessary overhead (access two memory words instead of one).
> 

I do not care about internal field world alignment to its natuaral boundary because this is how my implementation would parse the options/fields within - 
- read one ore more cache line worth of data from typically from the beginning of the extension header.
- parse the options
- when the option is identified as trace type the parsing logic that implements the trace-type will read the entire option length worth of data and split it out into in memory structure representation for consumption. 
I dont see a reason where a field is read at a time leading to suboptimal implementation where instead of 8 octets for an 8 octet field we end up reading 16 octets leading to performance penalty.
8200 does not have a MUST/SHOULD for aligning values within an option. Its upto the option designers. "Individual options may have specific alignment requirements, to ensure that multi-octet values within Option Data fields fall on natural boundaries."  and the Appendix A gives a typic

@mickeyspiegel or @barakgafni  can comment on the hardware implementation

**Comment by brockners** [comment]
draft-ietf-ippm-ioam-ipv6-options-01 already states that _"In addition, to maintain IPv6 extension header 8-octet alignment and avoid the need to add or remove padding at every hop, the Trace-Type for Incremental Tracing Option in IPv6 MUST be selected such that the IOAM node data length is a multiple of 8-octets."_ This means we already make explicit reference to RFC 8200 and the need to align to 8-byte boundaries. Just for reference: RFC 8200 states that _"Each extension header is an integer multiple of 8 octets long, in order to retain 8-octet alignment for subsequent headers."_ It does **not** say that every field in the extension header needs to be 8-bytes aligned, which IMHO also does not make sense, because it might grow extension headers unnecessarily due to a lot of padding being required in case smaller fields are carried.

From a hardware perspective, simple byte alignments are challenging (think TCP options). However, once you reach 4-byte alignment, there is diminishing returns to going to 8 byte alignment.  Consistency is probably more important, i.e. it's better if everyone agrees to the same alignment (either 4 byte or 8 byte).  For IOAM we've chosen 4 byte as the common denominator - which allows for efficient encap for several different protocols. And yes, for v6, we eventually need padding to get to the 8-byte boundary, but this is for v6 only.

**Comment by IurmanJ** [comment]
> It does **not** say that every field in the extension header needs to be 8-bytes aligned, which IMHO also does not make sense, because it might grow extension headers unnecessarily due to a lot of padding being required in case smaller fields are carried.

Actually, there is something about that but it is labelled as "desirable":

> One desirable feature is that any multi-octet fields within the
> Option Data area of an option be aligned on their natural
> boundaries, i.e., fields of width n octets should be placed at
> an integer multiple of n octets from the start of the
> Hop-by-Hop or Destination Options header, for n = 1, 2, 4, or
> 8.

As for the unnecessary padding, you wouldn't have the problem if all fields are ordered the way it is described (which is problematic with IOAM as options required may vary, hence my concern and my proposal). 

But, as I said, I understand that it makes things more complicated than it should be. I also understand that it is probably the best generic solution for all encapsulation protocols. I get that, totally. I just wanted to make sure that this decision is double-checked and everyone agrees. If so, I'm OK with it too. However, I still think that [draft-ietf-ippm-ioam-ipv6-options] should avoid talking about "4-octet fields" specifically, as there are some 8-octet fields too. Here, we are talking about 4n-aligned fields, which is different.

**Comment by brockners** [comment]
Closing the issue given that PR #167 was merged.
