### ISSUE TITLE
Substitute Option with Record in data draft

### ISSUE THREAD

**Issue by shwethab** [inband-oam/ietf#37]
Since no longer define the Trace, POT and E2E as TLVs how about calling them 

s/In-situ OAM Tracing Options/In-situ OAM Tracing Records
s/Pre-allocated Trace Option/Pre-allocated Trace Record
s/Incremental Trace Option/Incremental Trace Record
s/IOAM E2EOption/ IOAM E2E Record
and so on

This would make it easier to embed these trace records into an option format or in any other container that can have a length field.

**Comment by brockners** [comment]
IMHO it would be better to call them "data fields" instead of "data records". "data fields" is a really generic term, I moved away from the "records" terminology, because records are compound data structures (see https://en.wikipedia.org/wiki/Record_(computer_science)) which isn't generally the case (in case of tracing it is - but not so much for E2E...
